# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rapid7vmconsole
from rapid7vmconsole.models.report_repeat import ReportRepeat  # noqa: E501
from rapid7vmconsole.rest import ApiException


class TestReportRepeat(unittest.TestCase):
    """ReportRepeat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportRepeat(self):
        """Test ReportRepeat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rapid7vmconsole.models.report_repeat.ReportRepeat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
