# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scan_engine_api import ScanEngineApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScanEngineApi(unittest.TestCase):
    """ScanEngineApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.scan_engine_api.ScanEngineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_scan_engine_pool_scan_engine(self):
        """Test case for add_scan_engine_pool_scan_engine

        Engine Pool Engines  # noqa: E501
        """
        pass

    def test_create_scan_engine(self):
        """Test case for create_scan_engine

        Scan Engines  # noqa: E501
        """
        pass

    def test_create_scan_engine_pool(self):
        """Test case for create_scan_engine_pool

        Engine Pools  # noqa: E501
        """
        pass

    def test_delete_scan_engine(self):
        """Test case for delete_scan_engine

        Scan Engine  # noqa: E501
        """
        pass

    def test_get_assigned_engine_pools(self):
        """Test case for get_assigned_engine_pools

        Assigned Engine Pools  # noqa: E501
        """
        pass

    def test_get_engine_pool(self):
        """Test case for get_engine_pool

        Engine Pool  # noqa: E501
        """
        pass

    def test_get_scan_engine(self):
        """Test case for get_scan_engine

        Scan Engine  # noqa: E501
        """
        pass

    def test_get_scan_engine_pool_scan_engines(self):
        """Test case for get_scan_engine_pool_scan_engines

        Engine Pool Engines  # noqa: E501
        """
        pass

    def test_get_scan_engine_pool_sites(self):
        """Test case for get_scan_engine_pool_sites

        Engine Pool Sites  # noqa: E501
        """
        pass

    def test_get_scan_engine_pools(self):
        """Test case for get_scan_engine_pools

        Engine Pools  # noqa: E501
        """
        pass

    def test_get_scan_engine_scans(self):
        """Test case for get_scan_engine_scans

        Scan Engine Scans  # noqa: E501
        """
        pass

    def test_get_scan_engine_sites(self):
        """Test case for get_scan_engine_sites

        Scan Engine Sites  # noqa: E501
        """
        pass

    def test_get_scan_engines(self):
        """Test case for get_scan_engines

        Scan Engines  # noqa: E501
        """
        pass

    def test_remove_scan_engine_pool(self):
        """Test case for remove_scan_engine_pool

        Engine Pool  # noqa: E501
        """
        pass

    def test_remove_scan_engine_pool_scan_engine(self):
        """Test case for remove_scan_engine_pool_scan_engine

        Engine Pool Engines  # noqa: E501
        """
        pass

    def test_set_scan_engine_pool_scan_engines(self):
        """Test case for set_scan_engine_pool_scan_engines

        Engine Pool Engines  # noqa: E501
        """
        pass

    def test_update_scan_engine(self):
        """Test case for update_scan_engine

        Scan Engine  # noqa: E501
        """
        pass

    def test_update_scan_engine_pool(self):
        """Test case for update_scan_engine_pool

        Engine Pool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
