# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.asset_group_api import AssetGroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetGroupApi(unittest.TestCase):
    """AssetGroupApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.asset_group_api.AssetGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_asset_group_tag(self):
        """Test case for add_asset_group_tag

        Asset Group Tag  # noqa: E501
        """
        pass

    def test_add_asset_group_user(self):
        """Test case for add_asset_group_user

        Asset Group User  # noqa: E501
        """
        pass

    def test_add_asset_to_asset_group(self):
        """Test case for add_asset_to_asset_group

        Asset Group Asset  # noqa: E501
        """
        pass

    def test_create_asset_group(self):
        """Test case for create_asset_group

        Asset Groups  # noqa: E501
        """
        pass

    def test_delete_asset_group(self):
        """Test case for delete_asset_group

        Asset Group  # noqa: E501
        """
        pass

    def test_get_asset_group(self):
        """Test case for get_asset_group

        Asset Group  # noqa: E501
        """
        pass

    def test_get_asset_group_assets(self):
        """Test case for get_asset_group_assets

        Asset Group Assets  # noqa: E501
        """
        pass

    def test_get_asset_group_search_criteria(self):
        """Test case for get_asset_group_search_criteria

        Asset Group Search Criteria  # noqa: E501
        """
        pass

    def test_get_asset_group_tags(self):
        """Test case for get_asset_group_tags

        Asset Group Tags  # noqa: E501
        """
        pass

    def test_get_asset_group_users(self):
        """Test case for get_asset_group_users

        Asset Group Users  # noqa: E501
        """
        pass

    def test_get_asset_groups(self):
        """Test case for get_asset_groups

        Asset Groups  # noqa: E501
        """
        pass

    def test_remove_all_asset_group_tags(self):
        """Test case for remove_all_asset_group_tags

        Asset Group Tags  # noqa: E501
        """
        pass

    def test_remove_all_assets_from_asset_group(self):
        """Test case for remove_all_assets_from_asset_group

        Asset Group Assets  # noqa: E501
        """
        pass

    def test_remove_asset_from_asset_group(self):
        """Test case for remove_asset_from_asset_group

        Asset Group Asset  # noqa: E501
        """
        pass

    def test_remove_asset_group_tag(self):
        """Test case for remove_asset_group_tag

        Asset Group Tag  # noqa: E501
        """
        pass

    def test_remove_asset_group_user(self):
        """Test case for remove_asset_group_user

        Asset Group User  # noqa: E501
        """
        pass

    def test_set_asset_group_search_criteria(self):
        """Test case for set_asset_group_search_criteria

        Asset Group Search Criteria  # noqa: E501
        """
        pass

    def test_set_asset_group_tags(self):
        """Test case for set_asset_group_tags

        Asset Group Tags  # noqa: E501
        """
        pass

    def test_set_asset_group_users(self):
        """Test case for set_asset_group_users

        Asset Group Users  # noqa: E501
        """
        pass

    def test_update_asset_group(self):
        """Test case for update_asset_group

        Asset Group  # noqa: E501
        """
        pass

    def test_update_asset_group_assets(self):
        """Test case for update_asset_group_assets

        Asset Group Assets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
