# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.smtp_settings import SmtpSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestSmtpSettings(unittest.TestCase):
    """SmtpSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmtpSettings(self):
        """Test SmtpSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.smtp_settings.SmtpSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
