# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_settings import UpdateSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateSettings(unittest.TestCase):
    """UpdateSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSettings(self):
        """Test UpdateSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_settings.UpdateSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
