# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.administration_api import AdministrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.administration_api.AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_license(self):
        """Test case for activate_license

        License  # noqa: E501
        """
        pass

    def test_execute_command(self):
        """Test case for execute_command

        Console Commands  # noqa: E501
        """
        pass

    def test_get_info(self):
        """Test case for get_info

        Information  # noqa: E501
        """
        pass

    def test_get_license(self):
        """Test case for get_license

        License  # noqa: E501
        """
        pass

    def test_get_properties(self):
        """Test case for get_properties

        Properties  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
