# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.asset_discovery_api import AssetDiscoveryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetDiscoveryApi(unittest.TestCase):
    """AssetDiscoveryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.asset_discovery_api.AssetDiscoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sonar_query(self):
        """Test case for create_sonar_query

        Sonar Queries  # noqa: E501
        """
        pass

    def test_delete_sonar_query(self):
        """Test case for delete_sonar_query

        Sonar Query  # noqa: E501
        """
        pass

    def test_get_discovery_connection(self):
        """Test case for get_discovery_connection

        Discovery Connection  # noqa: E501
        """
        pass

    def test_get_discovery_connections(self):
        """Test case for get_discovery_connections

        Discovery Connections  # noqa: E501
        """
        pass

    def test_get_sonar_queries(self):
        """Test case for get_sonar_queries

        Sonar Queries  # noqa: E501
        """
        pass

    def test_get_sonar_query(self):
        """Test case for get_sonar_query

        Sonar Query  # noqa: E501
        """
        pass

    def test_get_sonar_query_assets(self):
        """Test case for get_sonar_query_assets

        Sonar Query Assets  # noqa: E501
        """
        pass

    def test_reconnect_discovery_connection(self):
        """Test case for reconnect_discovery_connection

        Discovery Connection Reconnect  # noqa: E501
        """
        pass

    def test_sonar_query_search(self):
        """Test case for sonar_query_search

        Sonar Query Search  # noqa: E501
        """
        pass

    def test_update_sonar_query(self):
        """Test case for update_sonar_query

        Sonar Query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
