# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unique_id import UniqueId  # noqa: E501
from swagger_client.rest import ApiException


class TestUniqueId(unittest.TestCase):
    """UniqueId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniqueId(self):
        """Test UniqueId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unique_id.UniqueId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
