# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resources_scan_engine import ResourcesScanEngine  # noqa: E501
from swagger_client.rest import ApiException


class TestResourcesScanEngine(unittest.TestCase):
    """ResourcesScanEngine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourcesScanEngine(self):
        """Test ResourcesScanEngine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resources_scan_engine.ResourcesScanEngine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
