# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.policy_rule_assessment_resource import PolicyRuleAssessmentResource  # noqa: E501
from swagger_client.rest import ApiException


class TestPolicyRuleAssessmentResource(unittest.TestCase):
    """PolicyRuleAssessmentResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyRuleAssessmentResource(self):
        """Test PolicyRuleAssessmentResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.policy_rule_assessment_resource.PolicyRuleAssessmentResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
