# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scan_template_discovery_performance_parallelism import ScanTemplateDiscoveryPerformanceParallelism  # noqa: E501
from swagger_client.rest import ApiException


class TestScanTemplateDiscoveryPerformanceParallelism(unittest.TestCase):
    """ScanTemplateDiscoveryPerformanceParallelism unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScanTemplateDiscoveryPerformanceParallelism(self):
        """Test ScanTemplateDiscoveryPerformanceParallelism"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scan_template_discovery_performance_parallelism.ScanTemplateDiscoveryPerformanceParallelism()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
