# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DiscoverySearchCriteria(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connection_type': 'str',
        'filters': 'list[SwaggerDiscoverySearchCriteriaFilter]',
        'match': 'str'
    }

    attribute_map = {
        'connection_type': 'connectionType',
        'filters': 'filters',
        'match': 'match'
    }

    def __init__(self, connection_type=None, filters=None, match=None):  # noqa: E501
        """DiscoverySearchCriteria - a model defined in Swagger"""  # noqa: E501

        self._connection_type = None
        self._filters = None
        self._match = None
        self.discriminator = None

        if connection_type is not None:
            self.connection_type = connection_type
        if filters is not None:
            self.filters = filters
        if match is not None:
            self.match = match

    @property
    def connection_type(self):
        """Gets the connection_type of this DiscoverySearchCriteria.  # noqa: E501

        The type of discovery connection configured for the site. This property only applies to dynamic sites.  # noqa: E501

        :return: The connection_type of this DiscoverySearchCriteria.  # noqa: E501
        :rtype: str
        """
        return self._connection_type

    @connection_type.setter
    def connection_type(self, connection_type):
        """Sets the connection_type of this DiscoverySearchCriteria.

        The type of discovery connection configured for the site. This property only applies to dynamic sites.  # noqa: E501

        :param connection_type: The connection_type of this DiscoverySearchCriteria.  # noqa: E501
        :type: str
        """
        allowed_values = ["activesync-ldap", "activesync-office365", "activesync-powershell", "aws", "dhcp", "sonar", "vsphere"]  # noqa: E501
        if connection_type not in allowed_values:
            raise ValueError(
                "Invalid value for `connection_type` ({0}), must be one of {1}"  # noqa: E501
                .format(connection_type, allowed_values)
            )

        self._connection_type = connection_type

    @property
    def filters(self):
        """Gets the filters of this DiscoverySearchCriteria.  # noqa: E501

        Filters used to match assets from a discovery connection. See <a href=\"#section/Responses/DiscoverySearchCriteria\">Discovery Connection Search Criteria</a> for more information on the structure and format.  # noqa: E501

        :return: The filters of this DiscoverySearchCriteria.  # noqa: E501
        :rtype: list[SwaggerDiscoverySearchCriteriaFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this DiscoverySearchCriteria.

        Filters used to match assets from a discovery connection. See <a href=\"#section/Responses/DiscoverySearchCriteria\">Discovery Connection Search Criteria</a> for more information on the structure and format.  # noqa: E501

        :param filters: The filters of this DiscoverySearchCriteria.  # noqa: E501
        :type: list[SwaggerDiscoverySearchCriteriaFilter]
        """

        self._filters = filters

    @property
    def match(self):
        """Gets the match of this DiscoverySearchCriteria.  # noqa: E501

        Operator to determine how to match filters. `all` requires that all filters match for an asset to be included. `any` requires only one filter to match for an asset to be included.  # noqa: E501

        :return: The match of this DiscoverySearchCriteria.  # noqa: E501
        :rtype: str
        """
        return self._match

    @match.setter
    def match(self, match):
        """Sets the match of this DiscoverySearchCriteria.

        Operator to determine how to match filters. `all` requires that all filters match for an asset to be included. `any` requires only one filter to match for an asset to be included.  # noqa: E501

        :param match: The match of this DiscoverySearchCriteria.  # noqa: E501
        :type: str
        """
        allowed_values = ["any", "all"]  # noqa: E501
        if match not in allowed_values:
            raise ValueError(
                "Invalid value for `match` ({0}), must be one of {1}"  # noqa: E501
                .format(match, allowed_values)
            )

        self._match = match

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiscoverySearchCriteria, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiscoverySearchCriteria):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
