# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JVMInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'start_time': 'str',
        'uptime': 'str',
        'vendor': 'str',
        'version': 'str'
    }

    attribute_map = {
        'name': 'name',
        'start_time': 'startTime',
        'uptime': 'uptime',
        'vendor': 'vendor',
        'version': 'version'
    }

    def __init__(self, name=None, start_time=None, uptime=None, vendor=None, version=None):  # noqa: E501
        """JVMInfo - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._start_time = None
        self._uptime = None
        self._vendor = None
        self._version = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if start_time is not None:
            self.start_time = start_time
        if uptime is not None:
            self.uptime = uptime
        if vendor is not None:
            self.vendor = vendor
        if version is not None:
            self.version = version

    @property
    def name(self):
        """Gets the name of this JVMInfo.  # noqa: E501

        The name of the Java Virtual Machine.  # noqa: E501

        :return: The name of this JVMInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JVMInfo.

        The name of the Java Virtual Machine.  # noqa: E501

        :param name: The name of this JVMInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def start_time(self):
        """Gets the start_time of this JVMInfo.  # noqa: E501

        The date and time the Java Virtual Machine last started.  # noqa: E501

        :return: The start_time of this JVMInfo.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this JVMInfo.

        The date and time the Java Virtual Machine last started.  # noqa: E501

        :param start_time: The start_time of this JVMInfo.  # noqa: E501
        :type: str
        """

        self._start_time = start_time

    @property
    def uptime(self):
        """Gets the uptime of this JVMInfo.  # noqa: E501

        Total up-time of the Java Virtual Machine, in ISO 8601 format. For example: `\"PT1H4M24.214S\"`.  # noqa: E501

        :return: The uptime of this JVMInfo.  # noqa: E501
        :rtype: str
        """
        return self._uptime

    @uptime.setter
    def uptime(self, uptime):
        """Sets the uptime of this JVMInfo.

        Total up-time of the Java Virtual Machine, in ISO 8601 format. For example: `\"PT1H4M24.214S\"`.  # noqa: E501

        :param uptime: The uptime of this JVMInfo.  # noqa: E501
        :type: str
        """

        self._uptime = uptime

    @property
    def vendor(self):
        """Gets the vendor of this JVMInfo.  # noqa: E501

        The vendor of the Java Virtual Machine.  # noqa: E501

        :return: The vendor of this JVMInfo.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this JVMInfo.

        The vendor of the Java Virtual Machine.  # noqa: E501

        :param vendor: The vendor of this JVMInfo.  # noqa: E501
        :type: str
        """

        self._vendor = vendor

    @property
    def version(self):
        """Gets the version of this JVMInfo.  # noqa: E501

        The version of the Java Virtual Machine.  # noqa: E501

        :return: The version of this JVMInfo.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this JVMInfo.

        The version of the Java Virtual Machine.  # noqa: E501

        :param version: The version of this JVMInfo.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JVMInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JVMInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
