# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LicensePolicyScanning(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'benchmarks': 'LicensePolicyScanningBenchmarks',
        'scanning': 'bool'
    }

    attribute_map = {
        'benchmarks': 'benchmarks',
        'scanning': 'scanning'
    }

    def __init__(self, benchmarks=None, scanning=None):  # noqa: E501
        """LicensePolicyScanning - a model defined in Swagger"""  # noqa: E501

        self._benchmarks = None
        self._scanning = None
        self.discriminator = None

        if benchmarks is not None:
            self.benchmarks = benchmarks
        if scanning is not None:
            self.scanning = scanning

    @property
    def benchmarks(self):
        """Gets the benchmarks of this LicensePolicyScanning.  # noqa: E501

        The benchmarks available to policy scan.  # noqa: E501

        :return: The benchmarks of this LicensePolicyScanning.  # noqa: E501
        :rtype: LicensePolicyScanningBenchmarks
        """
        return self._benchmarks

    @benchmarks.setter
    def benchmarks(self, benchmarks):
        """Sets the benchmarks of this LicensePolicyScanning.

        The benchmarks available to policy scan.  # noqa: E501

        :param benchmarks: The benchmarks of this LicensePolicyScanning.  # noqa: E501
        :type: LicensePolicyScanningBenchmarks
        """

        self._benchmarks = benchmarks

    @property
    def scanning(self):
        """Gets the scanning of this LicensePolicyScanning.  # noqa: E501

        Whether policy scanning is allowed.  # noqa: E501

        :return: The scanning of this LicensePolicyScanning.  # noqa: E501
        :rtype: bool
        """
        return self._scanning

    @scanning.setter
    def scanning(self, scanning):
        """Sets the scanning of this LicensePolicyScanning.

        Whether policy scanning is allowed.  # noqa: E501

        :param scanning: The scanning of this LicensePolicyScanning.  # noqa: E501
        :type: bool
        """

        self._scanning = scanning

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LicensePolicyScanning, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LicensePolicyScanning):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
