# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RiskTrendAllAssetsResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'bool',
        'trend': 'str'
    }

    attribute_map = {
        'total': 'total',
        'trend': 'trend'
    }

    def __init__(self, total=None, trend=None):  # noqa: E501
        """RiskTrendAllAssetsResource - a model defined in Swagger"""  # noqa: E501

        self._total = None
        self._trend = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if trend is not None:
            self.trend = trend

    @property
    def total(self):
        """Gets the total of this RiskTrendAllAssetsResource.  # noqa: E501

        Includes a trend for the total risk of all assets.  # noqa: E501

        :return: The total of this RiskTrendAllAssetsResource.  # noqa: E501
        :rtype: bool
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this RiskTrendAllAssetsResource.

        Includes a trend for the total risk of all assets.  # noqa: E501

        :param total: The total of this RiskTrendAllAssetsResource.  # noqa: E501
        :type: bool
        """

        self._total = total

    @property
    def trend(self):
        """Gets the trend of this RiskTrendAllAssetsResource.  # noqa: E501

        Whether to include a trend for average risk of all assets or the total number of assets.  # noqa: E501

        :return: The trend of this RiskTrendAllAssetsResource.  # noqa: E501
        :rtype: str
        """
        return self._trend

    @trend.setter
    def trend(self, trend):
        """Sets the trend of this RiskTrendAllAssetsResource.

        Whether to include a trend for average risk of all assets or the total number of assets.  # noqa: E501

        :param trend: The trend of this RiskTrendAllAssetsResource.  # noqa: E501
        :type: str
        """
        allowed_values = ["average-risk", "number-of-assets", "none"]  # noqa: E501
        if trend not in allowed_values:
            raise ValueError(
                "Invalid value for `trend` ({0}), must be one of {1}"  # noqa: E501
                .format(trend, allowed_values)
            )

        self._trend = trend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RiskTrendAllAssetsResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RiskTrendAllAssetsResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
