# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScanTemplateDiscoveryPerformanceParallelism(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'maximum': 'int',
        'minimum': 'int'
    }

    attribute_map = {
        'maximum': 'maximum',
        'minimum': 'minimum'
    }

    def __init__(self, maximum=None, minimum=None):  # noqa: E501
        """ScanTemplateDiscoveryPerformanceParallelism - a model defined in Swagger"""  # noqa: E501

        self._maximum = None
        self._minimum = None
        self.discriminator = None

        if maximum is not None:
            self.maximum = maximum
        if minimum is not None:
            self.minimum = minimum

    @property
    def maximum(self):
        """Gets the maximum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501

        The maximum number of discovery connection requests send in parallel. Defaults to `0`.  # noqa: E501

        :return: The maximum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501
        :rtype: int
        """
        return self._maximum

    @maximum.setter
    def maximum(self, maximum):
        """Sets the maximum of this ScanTemplateDiscoveryPerformanceParallelism.

        The maximum number of discovery connection requests send in parallel. Defaults to `0`.  # noqa: E501

        :param maximum: The maximum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501
        :type: int
        """
        if maximum is not None and maximum > 1000:  # noqa: E501
            raise ValueError("Invalid value for `maximum`, must be a value less than or equal to `1000`")  # noqa: E501
        if maximum is not None and maximum < 0:  # noqa: E501
            raise ValueError("Invalid value for `maximum`, must be a value greater than or equal to `0`")  # noqa: E501

        self._maximum = maximum

    @property
    def minimum(self):
        """Gets the minimum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501

        The minimum number of discovery connection requests send in parallel. Defaults to `0`.  # noqa: E501

        :return: The minimum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501
        :rtype: int
        """
        return self._minimum

    @minimum.setter
    def minimum(self, minimum):
        """Sets the minimum of this ScanTemplateDiscoveryPerformanceParallelism.

        The minimum number of discovery connection requests send in parallel. Defaults to `0`.  # noqa: E501

        :param minimum: The minimum of this ScanTemplateDiscoveryPerformanceParallelism.  # noqa: E501
        :type: int
        """
        if minimum is not None and minimum > 1000:  # noqa: E501
            raise ValueError("Invalid value for `minimum`, must be a value less than or equal to `1000`")  # noqa: E501
        if minimum is not None and minimum < 0:  # noqa: E501
            raise ValueError("Invalid value for `minimum`, must be a value greater than or equal to `0`")  # noqa: E501

        self._minimum = minimum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScanTemplateDiscoveryPerformanceParallelism, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScanTemplateDiscoveryPerformanceParallelism):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
