# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScanEvents(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'failed': 'bool',
        'paused': 'bool',
        'resumed': 'bool',
        'started': 'bool',
        'stopped': 'bool'
    }

    attribute_map = {
        'failed': 'failed',
        'paused': 'paused',
        'resumed': 'resumed',
        'started': 'started',
        'stopped': 'stopped'
    }

    def __init__(self, failed=None, paused=None, resumed=None, started=None, stopped=None):  # noqa: E501
        """ScanEvents - a model defined in Swagger"""  # noqa: E501

        self._failed = None
        self._paused = None
        self._resumed = None
        self._started = None
        self._stopped = None
        self.discriminator = None

        self.failed = failed
        self.paused = paused
        if resumed is not None:
            self.resumed = resumed
        self.started = started
        self.stopped = stopped

    @property
    def failed(self):
        """Gets the failed of this ScanEvents.  # noqa: E501

        Generates an alert when a scan fails. Default value is `false`.  # noqa: E501

        :return: The failed of this ScanEvents.  # noqa: E501
        :rtype: bool
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this ScanEvents.

        Generates an alert when a scan fails. Default value is `false`.  # noqa: E501

        :param failed: The failed of this ScanEvents.  # noqa: E501
        :type: bool
        """
        if failed is None:
            raise ValueError("Invalid value for `failed`, must not be `None`")  # noqa: E501

        self._failed = failed

    @property
    def paused(self):
        """Gets the paused of this ScanEvents.  # noqa: E501

        Generates an alert when a scan pauses. Default value is `false`.  # noqa: E501

        :return: The paused of this ScanEvents.  # noqa: E501
        :rtype: bool
        """
        return self._paused

    @paused.setter
    def paused(self, paused):
        """Sets the paused of this ScanEvents.

        Generates an alert when a scan pauses. Default value is `false`.  # noqa: E501

        :param paused: The paused of this ScanEvents.  # noqa: E501
        :type: bool
        """
        if paused is None:
            raise ValueError("Invalid value for `paused`, must not be `None`")  # noqa: E501

        self._paused = paused

    @property
    def resumed(self):
        """Gets the resumed of this ScanEvents.  # noqa: E501

        Generates an alert when a scan resumes. Default value is `false`.  # noqa: E501

        :return: The resumed of this ScanEvents.  # noqa: E501
        :rtype: bool
        """
        return self._resumed

    @resumed.setter
    def resumed(self, resumed):
        """Sets the resumed of this ScanEvents.

        Generates an alert when a scan resumes. Default value is `false`.  # noqa: E501

        :param resumed: The resumed of this ScanEvents.  # noqa: E501
        :type: bool
        """

        self._resumed = resumed

    @property
    def started(self):
        """Gets the started of this ScanEvents.  # noqa: E501

        Generates an alert when a scan starts. Default value is `false`.  # noqa: E501

        :return: The started of this ScanEvents.  # noqa: E501
        :rtype: bool
        """
        return self._started

    @started.setter
    def started(self, started):
        """Sets the started of this ScanEvents.

        Generates an alert when a scan starts. Default value is `false`.  # noqa: E501

        :param started: The started of this ScanEvents.  # noqa: E501
        :type: bool
        """
        if started is None:
            raise ValueError("Invalid value for `started`, must not be `None`")  # noqa: E501

        self._started = started

    @property
    def stopped(self):
        """Gets the stopped of this ScanEvents.  # noqa: E501

        Generates an alert when a scan stops. Default value is `false`.  # noqa: E501

        :return: The stopped of this ScanEvents.  # noqa: E501
        :rtype: bool
        """
        return self._stopped

    @stopped.setter
    def stopped(self, stopped):
        """Sets the stopped of this ScanEvents.

        Generates an alert when a scan stops. Default value is `false`.  # noqa: E501

        :param stopped: The stopped of this ScanEvents.  # noqa: E501
        :type: bool
        """
        if stopped is None:
            raise ValueError("Invalid value for `stopped`, must not be `None`")  # noqa: E501

        self._stopped = stopped

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScanEvents, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScanEvents):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
