# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Software(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'configurations': 'list[Configuration]',
        'cpe': 'SoftwareCpe',
        'description': 'str',
        'family': 'str',
        'id': 'int',
        'product': 'str',
        'type': 'str',
        'vendor': 'str',
        'version': 'str'
    }

    attribute_map = {
        'configurations': 'configurations',
        'cpe': 'cpe',
        'description': 'description',
        'family': 'family',
        'id': 'id',
        'product': 'product',
        'type': 'type',
        'vendor': 'vendor',
        'version': 'version'
    }

    def __init__(self, configurations=None, cpe=None, description=None, family=None, id=None, product=None, type=None, vendor=None, version=None):  # noqa: E501
        """Software - a model defined in Swagger"""  # noqa: E501

        self._configurations = None
        self._cpe = None
        self._description = None
        self._family = None
        self._id = None
        self._product = None
        self._type = None
        self._vendor = None
        self._version = None
        self.discriminator = None

        if configurations is not None:
            self.configurations = configurations
        if cpe is not None:
            self.cpe = cpe
        if description is not None:
            self.description = description
        if family is not None:
            self.family = family
        if id is not None:
            self.id = id
        if product is not None:
            self.product = product
        if type is not None:
            self.type = type
        if vendor is not None:
            self.vendor = vendor
        if version is not None:
            self.version = version

    @property
    def configurations(self):
        """Gets the configurations of this Software.  # noqa: E501

        The attributes of the software.  # noqa: E501

        :return: The configurations of this Software.  # noqa: E501
        :rtype: list[Configuration]
        """
        return self._configurations

    @configurations.setter
    def configurations(self, configurations):
        """Sets the configurations of this Software.

        The attributes of the software.  # noqa: E501

        :param configurations: The configurations of this Software.  # noqa: E501
        :type: list[Configuration]
        """

        self._configurations = configurations

    @property
    def cpe(self):
        """Gets the cpe of this Software.  # noqa: E501

        The Common Platform Enumeration (CPE) of the software.  # noqa: E501

        :return: The cpe of this Software.  # noqa: E501
        :rtype: SoftwareCpe
        """
        return self._cpe

    @cpe.setter
    def cpe(self, cpe):
        """Sets the cpe of this Software.

        The Common Platform Enumeration (CPE) of the software.  # noqa: E501

        :param cpe: The cpe of this Software.  # noqa: E501
        :type: SoftwareCpe
        """

        self._cpe = cpe

    @property
    def description(self):
        """Gets the description of this Software.  # noqa: E501

        The description of the software.  # noqa: E501

        :return: The description of this Software.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Software.

        The description of the software.  # noqa: E501

        :param description: The description of this Software.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def family(self):
        """Gets the family of this Software.  # noqa: E501

        The family of the software.  # noqa: E501

        :return: The family of this Software.  # noqa: E501
        :rtype: str
        """
        return self._family

    @family.setter
    def family(self, family):
        """Sets the family of this Software.

        The family of the software.  # noqa: E501

        :param family: The family of this Software.  # noqa: E501
        :type: str
        """

        self._family = family

    @property
    def id(self):
        """Gets the id of this Software.  # noqa: E501


        :return: The id of this Software.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Software.


        :param id: The id of this Software.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def product(self):
        """Gets the product of this Software.  # noqa: E501

        The product of the software.  # noqa: E501

        :return: The product of this Software.  # noqa: E501
        :rtype: str
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this Software.

        The product of the software.  # noqa: E501

        :param product: The product of this Software.  # noqa: E501
        :type: str
        """

        self._product = product

    @property
    def type(self):
        """Gets the type of this Software.  # noqa: E501

        The version of the software.  # noqa: E501

        :return: The type of this Software.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Software.

        The version of the software.  # noqa: E501

        :param type: The type of this Software.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def vendor(self):
        """Gets the vendor of this Software.  # noqa: E501

        The vendor of the software.  # noqa: E501

        :return: The vendor of this Software.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this Software.

        The vendor of the software.  # noqa: E501

        :param vendor: The vendor of this Software.  # noqa: E501
        :type: str
        """

        self._vendor = vendor

    @property
    def version(self):
        """Gets the version of this Software.  # noqa: E501

        The version of the software.  # noqa: E501

        :return: The version of this Software.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Software.

        The version of the software.  # noqa: E501

        :param version: The version of this Software.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Software, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Software):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
