# coding: utf-8

"""
    Python InsightVM API Client

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WebApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'pages': 'list[WebPage]',
        'root': 'str',
        'virtual_host': 'str'
    }

    attribute_map = {
        'id': 'id',
        'pages': 'pages',
        'root': 'root',
        'virtual_host': 'virtualHost'
    }

    def __init__(self, id=None, pages=None, root=None, virtual_host=None):  # noqa: E501
        """WebApplication - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._pages = None
        self._root = None
        self._virtual_host = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if pages is not None:
            self.pages = pages
        if root is not None:
            self.root = root
        if virtual_host is not None:
            self.virtual_host = virtual_host

    @property
    def id(self):
        """Gets the id of this WebApplication.  # noqa: E501

        The identifier of the web application.  # noqa: E501

        :return: The id of this WebApplication.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WebApplication.

        The identifier of the web application.  # noqa: E501

        :param id: The id of this WebApplication.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def pages(self):
        """Gets the pages of this WebApplication.  # noqa: E501

        The pages discovered on the web application.  # noqa: E501

        :return: The pages of this WebApplication.  # noqa: E501
        :rtype: list[WebPage]
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this WebApplication.

        The pages discovered on the web application.  # noqa: E501

        :param pages: The pages of this WebApplication.  # noqa: E501
        :type: list[WebPage]
        """

        self._pages = pages

    @property
    def root(self):
        """Gets the root of this WebApplication.  # noqa: E501

        The web root of the web application.  # noqa: E501

        :return: The root of this WebApplication.  # noqa: E501
        :rtype: str
        """
        return self._root

    @root.setter
    def root(self, root):
        """Sets the root of this WebApplication.

        The web root of the web application.  # noqa: E501

        :param root: The root of this WebApplication.  # noqa: E501
        :type: str
        """

        self._root = root

    @property
    def virtual_host(self):
        """Gets the virtual_host of this WebApplication.  # noqa: E501

        The virtual host of the web application.  # noqa: E501

        :return: The virtual_host of this WebApplication.  # noqa: E501
        :rtype: str
        """
        return self._virtual_host

    @virtual_host.setter
    def virtual_host(self, virtual_host):
        """Sets the virtual_host of this WebApplication.

        The virtual host of the web application.  # noqa: E501

        :param virtual_host: The virtual_host of this WebApplication.  # noqa: E501
        :type: str
        """

        self._virtual_host = virtual_host

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
